### PR TITLE
Automate README translations

### PR DESCRIPTION
**Pull request by itsamziii**
Draft PR for #600

> Some known issues that are to be fixed yet (this is just a draft PR)

- The workflow takes too long for translations, approx. ~10 mins, may batch translating content be helpful?
- Code blocks are exempted from translations due to unexpected translations of syntax
- Hyperlinks for TOC currently aren't being translated

Currently the translator uses Google AJAX Api for translations so the translations may not be "good". Best approach would perhaps be utilizing machine translation instead.

----

> [!IMPORTANT]
> Automates translation of `README.md` into multiple languages using a GitHub workflow and Python script, preserving code blocks and HTML tags.
> 
>   - **Workflow**:
>     - Adds `.github/workflows/translate-readme.yml` to automate translation of `README.md` on push.
>     - Uses `deep-translator` and `parmapper` for translation and parallel processing.
>     - Translates into Chinese, Japanese, and French.
>   - **Script**:
>     - `scripts/readme_translator.py` translates `README.md`, preserving code blocks and HTML tags.
>     - Uses `GoogleTranslator` from `deep-translator` for language translation.
>     - Saves translated files as `README-CN.md`, `README-JA.md`, `README-FR.md`.
>   - **Known Issues**:
>     - Translation process is slow (~10 mins), potential for batching.
>     - Code blocks and TOC links are not translated.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=julep-ai%2Fjulep&utm_source=github&utm_medium=referral)<sup> for 020e1024adb96317d29b30e4f27f1eaf4ce3ec0f. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by creatorrr** [comment]
Great work! @itsamziii 

For parallelizing you can use [parmapper library](https://github.com/Jwink3101/parmapper?tab=readme-ov-file#usage). Don't use the `translate_batch` method of `deep-translator`. They don't actually do any parallel work underneath, just `for i in ...` wrapper.

**Comment by creatorrr** [comment]
Perhaps something [like this](https://chatgpt.com/share/670864cc-74bc-8001-aeb1-e52973fc7c81):

```python
from deep_translator import GoogleTranslator
from pathlib import Path
import re
from typing import List
import parmapper
from functools import partial

def create_translator(target: str) -> GoogleTranslator:
    """
    Create a translator for a given target language.
    """
    return GoogleTranslator(source="en", target=target)

def translate_raw_html(translator: GoogleTranslator, html_content: str) -> str:
    """
    Translate a given raw html content using the provided translator, preserving HTML tags and newlines.
    """
    html_tags_pattern = r"(<[^>]+>)"
    segments = re.split(html_tags_pattern, html_content)

    translated_segments = []
    for segment in segments:
        if re.fullmatch(html_tags_pattern, segment):
            translated_segments.append(segment)
        else:
            try:
                if re.fullmatch(r'^[!"#$%&\'()*+,\-./:;<=>?@[\]^_`{|}~]+$', segment):
                    translated_segments.append(segment)
                    continue
                translated = translator.translate(segment)
                translated_segments.append(translated if translated else segment)
            except Exception as e:
                print(f"Error translating segment '{segment}': {e}")
                translated_segments.append(segment)
    return "".join(translated_segments)

def translate_readme(source: str, target: str) -> str:
    """
    Translate a README file from source to target language, preserving code blocks and newlines.
    """
    file_content = Path(source).read_text(encoding='utf-8')
    translator = create_translator(target)
    code_block_pattern = r"(```[\s\S]*?```|\n)"
    segments = re.split(code_block_pattern, file_content)
    
    # Prepare a partial function with the translator fixed
    translate_segment = partial(translate_raw_html, translator)
    
    # Parallelize the translation of segments
    translated_segments = list(parmapper.parmap(translate_segment, segments))
    
    return ''.join(translated_segments)

def save_translated_readme(translated_content: str, lang: str) -> None:
    """
    Save the translated README content to a file.
    """
    filename = f"README-{lang.split('-')[-1].upper()}.md"
    with open(filename, "w", encoding='utf-8') as file:
        file.write(translated_content)

def process_language(lang: str, source_file: str) -> None:
    """
    Process the translation for a single language.
    """
    translated_readme = translate_readme(source_file, lang)
    save_translated_readme(translated_readme, lang)

def main() -> None:
    """
    Main function to translate README.md to multiple languages.
    """
    source_file = "README.md"
    destination_langs = ["zh-CN", "ja", "fr"]
    
    # Prepare a partial function with the source_file fixed
    process_lang = partial(process_language, source_file=source_file)
    
    # Parallelize the translation of README for different languages
    list(parmapper.parmap(process_lang, destination_langs))

if __name__ == "__main__":
    main()
```

**Comment by creatorrr** [comment]
Don't worry about TOC section actually. They are autogenerated by a different github action so it's not a big deal

**Comment by itsamziii** [comment]
Alright, I can make this draft pr, up for review.

**Pull request merged**
