### PR TITLE
Added parsing for Brave Search Output

### PR DESCRIPTION
**Pull request by aarya-16**
Made changes so that a fully typed JSON object is returned by Brave Search .
This fixes issue #771 

----

> [!IMPORTANT]
> Parse Brave Search JSON output into `SearchResult` objects and update `BraveSearchOutput` to return a list of these objects.
> 
>   - **Behavior**:
>     - `search()` in `brave.py` now parses JSON results into `SearchResult` objects.
>     - `BraveSearchOutput` now returns a list of `SearchResult` instead of a single string.
>   - **Models**:
>     - Adds `SearchResult` model in `brave.py` with `title`, `link`, and `snippet` fields.
>     - Updates `BraveSearchOutput` in `brave.py` to use `List[SearchResult]` for `result`.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=julep-ai%2Fjulep&utm_source=github&utm_medium=referral)<sup> for 61e813a463268c8804c1ee0db265813342d15710. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by creatorrr** [comment]
Damn! Thank you, this is super helpful. We are doing some internal changes but once done, happy to merge :)

**Comment by creatorrr** [comment]
@Vedantsahai18 - can you please take a look, test and merge if works?

**Comment by aarya-16** [comment]
@creatorrr @Vedantsahai18 I see that some checks are not successful. Do you need me to do something from my end, or is it due to the internal changes ??

**Comment by Vedantsahai18** [comment]
@aarya-16 you need not add it from your end. I have pushed the internal changes that we pushed in your PR and will shortly merge it if all test passes.

**Pull request merged**
