### PR TITLE
Smart Home Automation Workflow using Julep Client API

### PR DESCRIPTION
**Pull request by SOHAIB-code-png**
This PR introduces a Python script for automating device control in a smart home environment using the Julep Client API. The script defines an AI agent designed to manage home automation workflows. It features the following key components:

**Agent Creation**: An AI agent is instantiated using the GPT-4o model, specialized in automating smart home tasks.
**Task Definition:** A device control task is defined using a YAML schema that handles the input of device ID and the action to be performed (e.g., turning a device on or off).
**Task Execution:** The script executes the task for controlling smart home devices and provides feedback on the action's success.

----

> [!IMPORTANT]
> Add Python script for smart home automation using Julep Client API with AI agent and device control task.
> 
>   - **Script Addition**:
>     - New script `15_smart__home__automation.py` added for smart home automation using Julep Client API.
>   - **Agent Creation**:
>     - AI agent created with `gpt-4o` model for smart home tasks.
>   - **Task Definition**:
>     - Device control task defined using YAML schema for `device_id` and `action`.
>   - **Task Execution**:
>     - Executes device control task and retrieves action status feedback.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=julep-ai%2Fjulep&utm_source=github&utm_medium=referral)<sup> for e6c34ea1673e43b15c367ff784d6602282c7a241. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by SOHAIB-code-png** [comment]
@creatorrr  please review this

**Comment by SOHAIB-code-png** [comment]
please review this @creatorrr

**Comment by SOHAIB-code-png** [comment]
please merge this if reviews are done

**Review by HamadaSalhab — COMMENTED** [review]
No added value from this workflow. Closing

**Pull request closed without merging**
