### PR TITLE
feat: add README-FR.md file

### LINKED ISSUE #606: Add README-FR.md file
Add a README-FR.md to Translation make our project more accessible to non-English speakers.

# Objective:
Add a French translation of the README file (README-FR.md) to make the project more accessible to French-speaking users and contributors, improving overall inclusivity and expanding the project's global reach.

# Implementation Suggestions:

**Create README-FR.md:**

- Start by creating a new file named README-FR.md in the root directory of the repository.
- Translate the content of the original README.md into French, ensuring clarity and accuracy in the translation.

**Consistency with English Version:**
- Ensure the French translation mirrors the structure, headings, and sections of the English README to maintain consistency across both documents.
- Keep technical terms like code snippets, commands, and file names in English where necessary, as these are often standard across languages.

**Add Language Switcher Links:**
- At the top of both README.md and README-FR.md, add links to switch between languages.

### PR DESCRIPTION
**Pull request by valay30**
## What does this PR do?
This PR add README-FR.md file.

Fixes #606

## Type of change
-New feature (non breaking change which adds functionality)

----

> [!IMPORTANT]
> Adds a French translation of the README and updates language navigation links in existing README files to include the French version.
> 
>   - **New File**:
>     - Adds `README-FR.md` for French translation of the README.
>   - **Link Updates**:
>     - Updates language navigation links in `README.md`, `README-CN.md`, and `README-JP.md` to include French translation.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=julep-ai%2Fjulep&utm_source=github&utm_medium=referral)<sup> for 72010c0571f7aae197224f17c879eacd5de329e9. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by Innovatorcloudy** [comment]
@valay30 Pr has already been created you can work on other issues

**Comment by valay30** [comment]
@Innovatorcloudy can you tell me the PR number

**Comment by kushal34712** [comment]
@valay30 it has been created by me #589 plz kindly close it

**Comment by creatorrr** [comment]
Actually we'd like to automate these translations. Closing in favor of https://github.com/julep-ai/julep/issues/600

**Pull request closed without merging**
